### ISSUE TITLE
Convert a number into binary

### ISSUE THREAD

**Issue by MANOJ-015** [bakiyaswanth/hacktoberfest21#5]
Can i work on **"Convert a number into binary program using c++"** 

Please assign me this issue.

**Comment by vivekarora-02** [comment]
Hey there, I would like to contribute to this issue. Can you please assign me this issue? 
 ThankYou!.

**Comment by ganesh1729ganesh** [comment]
I know how to convert a number to binary . I am interested in completing this algorithm. Can you please assign this to me?
